services:
  identity:
    build:
      context: .
      dockerfile: Dockerfile
    image: identity:latest
    container_name: identity
    restart: unless-stopped
    ports:
      - "127.0.0.1:7102:7102"
    environment:
      TZ: Europe/Istanbul
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL}
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    networks:
      - network_infra

networks:
  network_infra:
    external: true
