services:
  identity:
    build:
      context: .
      dockerfile: Dockerfile
    image: identity:latest
    container_name: identity
    restart: unless-stopped
    ports:
      - "7102:7102"
    networks:
      - network_infra

networks:
  network_infra:
    external: true