services:
  identity:
    build:
      context: .
      dockerfile: Dockerfile
    image: identity:latest
    container_name: identity
    restart: unless-stopped
    expose:
      - 7102
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - network_infra

networks:
  network_infra:
    external: true
