services:
  identity:
    image: identity:latest
    container_name: identity
    restart: unless-stopped
    ports:
      - "7102:7102"
    env_file:
      - /etc/infra-env/identity.env
    networks:
      - postgres_db_network
      - rabbitmq_default

networks:
  postgres_db_network:
    external: true
  rabbitmq_default:
    external: true