spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:identity}
    username: ${DATABASE_USERNAME:identity_admin}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      connection-init-sql: SET TIMEZONE TO 'Europe/Istanbul'
      pool-name: node-adapter-hikari
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:7102}


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      token-validity-in-minutes: ${JWT_TOKEN_VALIDITY_IN_MINUTES:60}
      refresh-token-validity-in-days: ${JWT_REFRESH_TOKEN_VALIDITY_IN_DAYS:7}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics


app:
  swagger:
    enabled: ${APP_SWAGGER_ENABLED:true}
  admin:
    registration:
      enabled: ${APP_ADMIN_REGISTRATION_ENABLED:true}

mail:
  enabled: ${MAIL_ENABLED:true}
  from: ${MAIL_FROM}
  admin-redirect-address: ${MAIL_ADMIN_REDIRECT_ADDRESS:hakan.guneser@gmail.com}
  smtp:
    host: ${MAIL_SMTP_HOST:smtp.gmail.com}
    port: ${MAIL_SMTP_PORT:587}
    username: ${MAIL_FROM}
    password: ${MAIL_PASSWORD}
